window.KOAUS_PRODUCTS = [
  {
    id: "litem-neo-desk-organizer",
    name: "Neo Desk Organizer",
    originalName: "네오 데스크 오거나이저",
    maker: "LITEM",
    category: "Desk Goods",
    tag: "29CM desk pick",
    price: 11,
    originalPrice: 16400,
    status: "Seoul pick",
    description: "A modular organizer that keeps pens, notes, and daily tools visible but neatly divided.",
    image: "images/product-desk-organizer.jpg",
    sourceName: "29CM",
    sourceUrl: "https://www.29cm.co.kr/products/1674537",
  },
  {
    id: "facade-breeze-tote",
    name: "Breeze Tote Bag",
    originalName: "브리즈 토트백_forest",
    maker: "Facade Pattern",
    category: "Fashion",
    tag: "29CM fashion pick",
    price: 40,
    originalPrice: 58000,
    status: "Pre-order",
    description: "A light nylon tote with a compact profile, contrast trim, and an inner zip pocket.",
    image: "images/product-breeze-tote.jpg",
    sourceName: "29CM",
    sourceUrl: "https://www.29cm.co.kr/products/2498328",
  },
  {
    id: "trolls-2026-diary",
    name: "2026 Thread-bound Diary",
    originalName: "2026 Diary",
    maker: "Trolls Paper",
    category: "Stationery",
    tag: "Seoul paper",
    price: 12,
    originalPrice: 18000,
    status: "Seoul pick",
    description: "A fountain-pen-friendly dated diary with tactile paper and a flat-opening binding.",
    image: "images/product-diary.jpg",
    sourceName: "Ohouse",
    sourceUrl: "https://store.ohou.se/goods/3790452",
  },
  {
    id: "position-stone-plate",
    name: "Stone & Plate Object",
    originalName: "Stone and Plate_Ivory",
    maker: "Position",
    category: "Lifestyle",
    tag: "29CM room pick",
    price: 10,
    originalPrice: 14500,
    status: "Seoul pick",
    description: "A small sculptural plaster plate for a candle, jewelry, or a quiet bedside object.",
    image: "images/product-stone-plate.jpg",
    sourceName: "29CM",
    sourceUrl: "https://www.29cm.co.kr/products/2676481",
  },
  {
    id: "lumir-table-lamp",
    name: "Lumir R Steel Table Lamp",
    originalName: "루미르R 테이블 램프 스틸 화이트",
    maker: "LUMIR",
    category: "Lifestyle",
    tag: "Made in Korea",
    price: 123,
    originalPrice: 180000,
    status: "Pre-order",
    description: "The drop's single lighting pick: sculptural steel designed and made in Korea.",
    image: "images/product-lamp.jpg",
    sourceName: "Ohouse",
    sourceUrl: "https://store.ohou.se/goods/469033",
  },
  {
    id: "muzik-tiger-mug",
    name: "Chubby Tiger Ceramic Mug",
    originalName: "뚱랑이 세라믹 머그컵 4종",
    maker: "Muzik Tiger",
    category: "Gift Set",
    tag: "Giftable",
    price: 10,
    originalPrice: 15000,
    status: "Seoul pick",
    description: "A cheerful 400 ml ceramic character mug made for small everyday gift moments.",
    image: "images/product-tiger-mug.jpg",
    sourceName: "Ohouse",
    sourceUrl: "https://store.ohou.se/goods/2301344",
  },
  {
    id: "facade-vintage-cabin-bag",
    name: "Vintage Cabin Bag",
    originalName: "빈티지 캐빈 백_black",
    maker: "Facade Pattern",
    category: "Fashion",
    tag: "29CM fashion pick",
    price: 122,
    originalPrice: 178000,
    status: "Pre-order",
    description: "A compact vegetable-tanned sheepskin bag with a zip closure and adjustable strap.",
    image: "images/product-cabin-bag.jpg",
    sourceName: "29CM",
    sourceUrl: "https://www.29cm.co.kr/products/2498321",
  },
  {
    id: "gonggi-oblong-mug",
    name: "Oblong Mug · Stone Beige",
    originalName: "OBLONG MUG_Stone Beige",
    maker: "Jiseungmin's Gonggi",
    category: "Gift Set",
    tag: "29CM ceramic pick",
    price: 38,
    originalPrice: 55000,
    status: "Seoul pick",
    description: "A softly rounded stone-beige mug that feels like a small ceramic object in the hand.",
    image: "images/product-oblong-mug.png",
    sourceName: "29CM",
    sourceUrl: "https://www.29cm.co.kr/products/2102367",
  },
  {
    id: "append-pencil-pouch",
    name: "Terry Pencil Pouch",
    originalName: "펜슬 파우치 필통 pencil pouch (black)",
    maker: "Append",
    category: "Desk Goods",
    tag: "Made in Korea",
    price: 9,
    originalPrice: 13500,
    status: "Coming soon",
    description: "A tall terry-cloth pencil pouch with a water-resistant lining for up to 20 pens.",
    image: "images/product-pencil-pouch.jpg",
    sourceName: "Ohouse",
    sourceUrl: "https://store.ohou.se/goods/3777117",
  },
  {
    id: "pondang-mug-set",
    name: "Pondang Mug & Coaster Set",
    originalName: "퐁당 세라믹 머그&패브릭 코스터 세트",
    maker: "275PROJECT",
    category: "Gift Set",
    tag: "Bundle-ready",
    price: 16,
    originalPrice: 23400,
    status: "Pre-order",
    description: "A coordinated ceramic mug and soft fabric coaster set ready for gifting.",
    image: "images/product-mug-set.jpg",
    sourceName: "Ohouse",
    sourceUrl: "https://store.ohou.se/goods/4019381",
  },
];
